name: llm-playground
channels:
  - conda-forge
  - pytorch
dependencies:
  - huggingface::transformers
  - flake8
  - ipykernel
  - jupyter
  - langchain-core
  - langgraph>0.2.27
  - pip
  - pytorch::pytorch
  - python>=3.9
  - python-dotenv
  - pip:
    - langchain[openai]